name: CI&&CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: Dependent environment
        run: |
          npm i -g @angular/cli
          npm i
      
      - name: Compile
        run: |
          npm run build
      
      - name: Deploy
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: dist\nice-blockly
          remote: ${{ secrets.TARGET }}
          host: ${{ secrets.HOST }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATEKEY }}
